import { StyleSheet } from '@react-pdf/renderer'

/**
 * Charte couleur PDF, alignée sur la charte web.
 * Brand: #0077B6 — Hover: #005F96 — Light: #E0F0FA
 */
export const COLORS = {
  brand: '#0077B6',
  brandHover: '#005F96',
  brandLight: '#E0F0FA',
  fg: '#0F172A',
  muted: '#64748B',
  secondary: '#475569',
  border: '#E2E8F0',
  surface: '#F8FAFC',
  white: '#FFFFFF',
  positive: '#16A34A',
  negative: '#DC2626',
  warning: '#D97706',
} as const

export const styles = StyleSheet.create({
  page: {
    paddingTop: 56,
    paddingBottom: 64,
    paddingHorizontal: 48,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: COLORS.fg,
    backgroundColor: COLORS.white,
  },
  brandBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 6,
    backgroundColor: COLORS.brand,
  },
  pageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  brandName: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.brand,
    letterSpacing: 1.5,
  },
  pageHeaderRight: {
    fontSize: 9,
    color: COLORS.muted,
    textAlign: 'right',
  },
  title: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.fg,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 13,
    color: COLORS.muted,
    marginBottom: 28,
  },
  bigValueBox: {
    backgroundColor: COLORS.brandLight,
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    marginBottom: 24,
  },
  bigValueLabel: {
    fontSize: 10,
    color: COLORS.muted,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: 'Helvetica-Bold',
  },
  bigValueAmount: {
    fontSize: 36,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.brand,
    marginBottom: 8,
  },
  bigValueRange: {
    fontSize: 12,
    color: COLORS.fg,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.brand,
    marginTop: 16,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 10,
    lineHeight: 1.5,
    color: COLORS.fg,
    marginBottom: 6,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 4,
  },
  rowLabel: {
    color: COLORS.muted,
    fontSize: 10,
    flex: 1,
    paddingRight: 8,
  },
  rowValue: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'right',
  },
  rowDivider: {
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    marginTop: 6,
    paddingTop: 6,
  },
  bullet: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  bulletDot: {
    width: 14,
    color: COLORS.brand,
    fontFamily: 'Helvetica-Bold',
  },
  bulletText: {
    flex: 1,
    fontSize: 10,
    lineHeight: 1.4,
  },
  cta: {
    marginTop: 24,
    backgroundColor: COLORS.brand,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  ctaText: {
    color: COLORS.white,
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
  },
  ctaSubtext: {
    color: COLORS.white,
    fontSize: 9,
    marginTop: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: COLORS.muted,
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 8,
  },
  scoreBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.brandLight,
    padding: 24,
    borderRadius: 12,
    marginBottom: 24,
  },
  scoreInline: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  scoreBig: {
    fontSize: 64,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.brand,
  },
  scoreOutOf: {
    fontSize: 18,
    color: COLORS.muted,
    marginLeft: 4,
  },
  scoreLabelText: {
    fontSize: 11,
    color: COLORS.fg,
    marginLeft: 24,
    lineHeight: 1.5,
    flex: 1,
  },
  scoreSubrow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  scoreSub: {
    flex: 1,
    padding: 12,
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  scoreSubLabel: {
    fontSize: 9,
    color: COLORS.muted,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  scoreSubValue: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.fg,
  },
  scoreBar: {
    height: 6,
    backgroundColor: COLORS.border,
    borderRadius: 3,
    marginTop: 6,
  },
  scoreBarFill: {
    height: 6,
    backgroundColor: COLORS.brand,
    borderRadius: 3,
  },
})
