import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, MapPin, Phone } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { env } from '@/lib/env'
import { siteVisuals } from '@/lib/site-visuals'

export const metadata: Metadata = {
  title: 'Mon approche — Alexandre Lopez, conseiller immobilier iad Provence Verte & Verdon',
  description: 'Alexandre Lopez, conseiller immobilier iad France en Provence Verte et Verdon. Une approche locale, claire et structurée pour vendre, acheter ou estimer un bien.',
  alternates: { canonical: (env.app.siteUrl || 'https://alexandrelopez.fr') + '/a-propos' },
}
const PHONE_RAW = '+33613180168'
const PHONE_DISPLAY = '06 13 18 01 68'
const personJsonLd = { '@context': 'https://schema.org', '@type': 'Person', name: 'Alexandre Lopez', jobTitle: 'Conseiller immobilier iad France', description: 'Conseiller immobilier iad France en Provence Verte et Verdon, spécialisé dans la vente, l\'achat et l\'estimation de biens immobiliers.', telephone: PHONE_RAW, areaServed: ['Provence Verte', 'Verdon', 'Provence Verdon', 'Brignoles', 'Saint-Maximin-la-Sainte-Baume', 'Barjols', 'Cotignac', 'Rians', 'Aups', 'Salernes', 'Montmeyan'], address: { '@type': 'PostalAddress', addressRegion: 'Var', addressCountry: 'FR' }, worksFor: { '@type': 'Organization', name: 'iad France', url: 'https://www.iadfrance.fr' } }
const VALEURS = [
  { titre: 'Transparence', texte: 'Un avis clair et argumenté, sans prix gonflé pour séduire artificiellement.' },
  { titre: 'Méthode', texte: 'Une lecture structurée du bien, du marché, du délai et de votre objectif.' },
  { titre: 'Ancrage local', texte: 'Une connaissance de la Provence Verte & Verdon et des écarts entre micro-marchés.' },
  { titre: 'Suivi', texte: 'Un contact direct, des étapes claires et un accompagnement jusqu’à la décision.' },
]
const COMMUNES = ['Brignoles', 'Saint-Maximin', 'Barjols', 'Cotignac', 'Montmeyan', 'Rians', 'Aups', 'Salernes', 'Tavernes', 'Vinon-sur-Verdon']
function buildInnerHtml(data: object) { return { __html: JSON.stringify(data) } }

export default function AProposPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={buildInnerHtml(personJsonLd)} />
      <section className="relative min-h-[44rem] overflow-hidden px-6 pb-16 pt-28 text-white lg:min-h-screen lg:pb-24 lg:pt-36"><Image src={siteVisuals.contactVillage.src} alt={siteVisuals.contactVillage.alt} fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#101828]/88 via-[#101828]/58 to-[#101828]/18" /><div className="absolute inset-0 bg-gradient-to-t from-[#101828]/54 via-transparent to-[#101828]/20" /><div className="relative mx-auto flex min-h-[32rem] max-w-7xl items-end lg:min-h-[42rem]"><div className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full bg-white/12 px-4 py-2 text-sm font-semibold text-white shadow-sm backdrop-blur"><MapPin size={15} className="text-brand-light" /> Provence Verte & Verdon</div><h1 className="max-w-3xl text-4xl font-bold leading-[1.04] tracking-[-0.05em] text-white md:text-6xl lg:text-7xl">Une approche locale, claire et <span className="text-brand-light">exigeante</span>.</h1><div className="mt-7 max-w-2xl space-y-4 text-lg leading-relaxed text-white/84 md:text-xl"><p>Je suis Alexandre Lopez, conseiller immobilier iad France en Provence Verte & Verdon.</p><p>Mon rôle est de vous aider à vendre, acheter ou estimer avec les bonnes informations : le bien, le secteur, le timing, les objectifs et les vrais leviers de décision.</p></div><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Button asChild variant="primary" size="lg"><Link href="/outils">Commencer avec les outils <ArrowRight size={16} /></Link></Button><a href={'tel:' + PHONE_RAW} className="inline-flex items-center justify-center gap-2 rounded-full border-2 border-white/80 px-7 py-4 text-sm font-bold text-white transition-all hover:-translate-y-0.5 hover:bg-white hover:text-foreground"><Phone size={16} /> {PHONE_DISPLAY}</a></div></div></div></section>
      <section className="bg-white px-6 py-20"><div className="mx-auto grid max-w-7xl items-start gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="mb-4 text-sm font-bold uppercase tracking-[0.22em] text-brand">Ce qui me guide</p><h2 className="text-3xl font-bold leading-tight tracking-[-0.04em] text-foreground md:text-5xl">Des repères solides pour avancer.</h2><p className="mt-5 text-lg leading-relaxed text-muted">Le bon accompagnement ne consiste pas à pousser une décision. Il consiste à rendre le projet plus lisible.</p></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2">{VALEURS.map((v) => <div key={v.titre} className="rounded-2xl bg-[#f4f7f8] p-7 shadow-sm transition-all hover:-translate-y-2 hover:shadow-xl"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-white text-brand shadow-sm"><CheckCircle2 size={20} /></div><h3 className="text-xl font-bold text-foreground">{v.titre}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{v.texte}</p></div>)}</div></div></section>
      <section className="relative min-h-[32rem] overflow-hidden px-6 py-24 text-white md:min-h-[40rem] md:py-32"><Image src={siteVisuals.cotignacHouse.src} alt={siteVisuals.cotignacHouse.alt} fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#101828]/82 via-[#101828]/42 to-transparent" /><div className="relative mx-auto flex min-h-[24rem] max-w-7xl items-end md:min-h-[28rem]"><div className="max-w-3xl"><p className="mb-4 inline-flex rounded-full bg-white/12 px-4 py-2 text-sm font-bold uppercase tracking-[0.18em] text-brand-light backdrop-blur">Parcours</p><h2 className="text-4xl font-bold leading-tight tracking-[-0.045em] md:text-6xl">De la stratégie à l’immobilier de proximité.</h2><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/82">Mon parcours en stratégie et organisation m’a donné une méthode : structurer, comparer, décider. Je l’applique aujourd’hui à l’immobilier local, avec une approche humaine et concrète.</p></div></div></section>
      <section className="bg-white px-6 py-20"><div className="mx-auto max-w-4xl text-center"><div className="mb-4 flex items-center justify-center gap-2 text-brand"><MapPin size={18} /><p className="text-sm font-bold uppercase tracking-[0.22em]">Zone d’intervention</p></div><h2 className="text-3xl font-bold tracking-[-0.04em] text-foreground md:text-5xl">Provence Verte & Verdon</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-muted">J’interviens sur les communes de Provence Verte et du Verdon, avec une lecture locale des biens, des prix et des attentes des acquéreurs.</p><div className="mt-9 flex flex-wrap justify-center gap-2">{COMMUNES.map((c) => { const slug = c.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '-'); return <Link key={c} href={'/immobilier/' + slug} className="rounded-full bg-[#f4f7f8] px-4 py-2 text-sm font-semibold text-muted transition-colors hover:bg-brand hover:text-white">{c}</Link> })}</div></div></section>
      <section className="bg-gradient-to-br from-brand to-brand-hover px-6 py-20"><div className="mx-auto max-w-4xl text-center"><p className="mb-3 text-sm font-bold uppercase tracking-[0.22em] text-white/80">Travaillons ensemble</p><h2 className="text-3xl font-bold tracking-[-0.04em] text-white md:text-5xl">Un projet immobilier ?</h2><p className="mx-auto mt-5 max-w-xl text-lg leading-relaxed text-white/90">Estimation, vente, achat ou simple question sur le marché en Provence Verte & Verdon. Réponse personnalisée, sans engagement.</p><div className="mt-8"><Link href="/outils" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-8 py-4 text-sm font-bold text-brand transition-colors hover:bg-[#f4f7f8]">Commencer avec les outils <ArrowRight size={16} /></Link></div></div></section>
    </>
  )
}
